name: Code quality
on: [ push, pull_request ]
permissions:
  contents: read

jobs:
  code-quality:
    name: Lint source code scss/js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      uses: Borales/actions-yarn@v3
      with:
        cmd: --cwd ./dev install

    - name: Lint files
      uses: Borales/actions-yarn@v3
      with:
        cmd: --cwd ./dev gh-lint

