name: Code quality

on: ['push', 'pull_request']

jobs:
  code-quality:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Setup NPM
        run: npm install -g npm@6

    - name: Lint files
      run: |
        cd ./_dev && npm install && npm run gh-lint
